// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASN6GATF_FlE2N6oaAF9Hn4uGSEct6jJQ',
    appId: '1:416442513165:android:73a9f84273f78328fd6244',
    messagingSenderId: '416442513165',
    projectId: 'habitual-heart',
    storageBucket: 'habitual-heart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzOpUFDxrlvEDM4v0yuluVqWe6NW_-d5Y',
    appId: '1:416442513165:ios:d8cda800630738a3fd6244',
    messagingSenderId: '416442513165',
    projectId: 'habitual-heart',
    storageBucket: 'habitual-heart.appspot.com',
    androidClientId: '416442513165-jid8hae7knfrsssai8v4itp5s9b6f2v5.apps.googleusercontent.com',
    iosClientId: '416442513165-4lf5bb6rg8p4fp04ip8j2e4sd79sat9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitualheart.habitualHeartApp',
  );
}
